Feature/651 merge custom properties of config file
ThreeMammals/Ocelot pull request #1183
Opened 2020-04-07 19:45 UTC by jlukawska

Fixes / New Feature #651 Extending ReRoute Configuration

## Proposed Changes

  -  The whole sections of config files (with custom properties) are merged.

2023-07-26 15:18 UTC, raman-m commented
Congrats, @jlukawska ! 🎉 
Your [feature branch](/jlukawska/Ocelot/tree/feature/651-merge-custom-properties) has been rebased onto **ThreeMammals:develop**.

We can go with code review now...

2023-07-28 07:19 UTC, RaynaldM approved these changes

2023-08-02 16:47 UTC, wast approved these changes

2023-08-03 18:24 UTC, raman-m commented
@nurhat
As the #651 issue author, could you review this solution please?
Will the solution be useful and helpful for your daily gateway development?

2023-08-03 18:30 UTC, raman-m commented
@RaynaldM @wast 
You are great approvers! 🥇 
Seems like @jlukawska is making breaking changes and you've approved them. 🤣 
I am not sure about changes that they're breaking, but I will review the code thorougly. 👇

2023-08-03 19:06 UTC, raman-m requested changes
How to read `CustomStrategyProperty` value of the route in run-time?

2023-08-03 19:27 UTC, raman-m commented
@nurhat @jlukawska 
I would like to understand, how useful this feature for real world user scenarios.

## User case 1
### Change behavior of PollyQoSProvider 
Given, I wish to override behavior of the [Quality of Service](https://ocelot.readthedocs.io/en/latest/features/qualityofservice.html) feature by changes in [PollyQoSProvider](../blob/develop/src/Ocelot.Provider.Polly/PollyQoSProvider.cs#L14) and/or [AddPolly](../blob/develop/src/Ocelot.Provider.Polly/OcelotBuilderExtensions.cs#L25) and/or [PollyCircuitBreakingDelegatingHandler](../blob/develop/src/Ocelot.Provider.Polly/PollyCircuitBreakingDelegatingHandler.cs#L12) classes.
And, I will define custom property of the route for custom QoS overriding.
And, I will read the custom property from `DownstreamRoute` object.
When, I read the custom property the custom property from `DownstreamRoute` object.
Then, I get stuck! 😉 

### Question:
- How to read custom property from `DownstreamRoute` object?
- How and what interface do I need to inject to a service class to be able to read custom property from `DownstreamRoute` object?

---

@RaynaldM @wast 
Let's have a fun! 😄

2023-11-06 11:28 UTC, raman-m commented on test/Ocelot.AcceptanceTests/ConfigurationMergeTests.cs
> +                .And(x => ThenConfigContentShouldBeMergedWithRoutesCustomProperties())
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1183/commits/d5bb16e56107600ae5a83d7f9a5f96385408fea1 ✔️

2023-11-06 11:29 UTC, raman-m commented on test/Ocelot.AcceptanceTests/ConfigurationMergeTests.cs
> +        }
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1183/commits/d5bb16e56107600ae5a83d7f9a5f96385408fea1 ✔️

2024-05-16 17:47 UTC, jlukawska commented
@raman-m, I marked this PR as a draft, because I am not sure if the conflicts are resolved correctly (even though the tests passed correctly). It wasn't that easy ;) I'd have to revise the code, understand the changes from develop branch and maybe the PR code would have to be improved. 
Apart from that, would this PR be helpful for anyone? I proposed it 4 years ago and the issue reporter no longer responds.

2024-05-28 09:05 UTC, raman-m commented
Understood, Jolanta. It seems you're uncertain and wish to further develop. I also notice that many PR files contain a fake diff indicating numerous merge conflicts were resolved.

**Here's what I suggest:**
- Create a new feature branch from develop. Your forked repo develop is synced.
- Clone the second repository for manual file operations.
- Transfer all changes from the old feature branch to the new one using a file manager (TotalCommander is my choice, an old school tool with a dual-pane interface vs useful comparison command).
- Open a new PR after confirming successful compilation and passing tests.
- Close this old PR and reference the new one.

Does this sound like a good approach?

2024-11-11 12:57 UTC, raman-m commented
🆗 I'm going to rebase the branch...

2024-11-11 16:17 UTC, raman-m commented
@jlukawska commented [on May 16, 2024](https://github.com/ThreeMammals/Ocelot/pull/1183#issuecomment-2115855052)
> I am not sure if the conflicts are resolved correctly (even though the tests passed correctly). It wasn't that easy ;)

I've rebased the feature branch today and addressed the failed tests. The entire code appears to be in good shape. I will provide my final code review later, after receiving feedback from the team. However, the current acceptance test confirms the successful merging of JSON. More tests are necessary, and it seems they will be essential for the upcoming C# helpers that will be reused in the actual code of middlewares, similar to how the Metadata-helpers function.

> Apart from that, would this PR be helpful for anyone? 

Indeed, the question of whether this PR would be beneficial to anyone is quite pertinent, especially after the introduction of the [Route Metadata](https://ocelot.readthedocs.io/en/latest/features/configuration.html#route-metadata) feature (aka [Metadata](https://ocelot.readthedocs.io/en/latest/features/metadata.html)). While some developers may not favor storing additional route data in the `Metadata` property, the direct inclusion of properties in JSON remains a sought-after feature, as suggested by your PR. The primary challenge lies in crafting comprehensive documentation before we can develop truly useful C# helpers, potentially surpassing the current Metadata logic.

> I proposed it 4 years ago and the issue reporter no longer responds.

Mr. @nurhat didn't even reply to me, which suggests he might have used a work account linked to a corporate email. Developers often change jobs and employers, along with their work emails. Regardless, I'll assume the role of the author. 😉

2024-11-11 16:22 UTC, raman-m reviewed
### Ready for Code Review❕

2024-11-11 16:40 UTC, raman-m commented
### Dependencies
- #2125

2026-01-12 16:42 UTC, raman-m commented
## Ready for code review ✔️ 
- [ ] Require code coverage improvement

2026-01-14 07:11 UTC, RaynaldM approved these changes

2026-07-03 18:04 UTC, raman-m requested changes
As I mentioned earlier, **we should introduce helper methods.** The current implementation shows that the feature works technically, but we still need public helpers to read custom properties from route data (similar to the extension readers provided for the [Metadata](https://github.com/ThreeMammals/Ocelot/tree/develop/src/Metadata) feature).

After these helpers are in place, we must update the documentation. This is essential — without proper docs, the feature will remain hidden and unusable for the community.

Additionally, I suggest that we address the following issues below 👇

2026-07-03 18:04 UTC, raman-m commented on acceptance/Configuration/ConfigurationBuilderExtensionsTests.cs
Better to move to `acceptance/Configuration/ConfigurationMergeTests.cs` with the ConfigurationMergeTests class being responsible for testing of Configuration Merge feat.

2026-07-03 18:04 UTC, raman-m commented on src/Administration/FileConfigurationController.cs
> +            return BadRequest(e.GetMessages());
Not sure about this. GetMessages() returns a string — so we lose the exception type. Should we use ToString() instead to keep the type info?

2026-07-03 18:04 UTC, raman-m commented on src/Administration/FileConfigurationController.cs
> +            return BadRequest(e.GetMessages());
Seems previous `ToString()` was right.

2026-07-03 18:04 UTC, raman-m commented on src/Configuration/Repository/FileConfigurationPoller.cs
> +                _logger.LogWarning(() => $"{nameof(Poll)}: Error getting {nameof(FileConfiguration)} -> {e.AllMessages}.");
We lose type info and call stack here. `ToString()` has both.
Losing call stack is fine, but we need type info. Refactor `AllMessages`?

2026-07-03 18:04 UTC, raman-m commented on src/DependencyInjection/ConfigurationBuilderExtensions.cs
> +    public static IConfigurationBuilder AddOcelot(this IConfigurationBuilder builder, JObject fileConfiguration)
Method is public. Lack of XML-documentation

2026-07-03 18:04 UTC, raman-m commented on src/DependencyInjection/ConfigurationBuilderExtensions.cs
> +        => SerializeToFile(builder, fileConfiguration);
Forgot to propagate `string primaryConfigFile` argument into `SerializeToFile(...)` method ❗

2026-07-03 18:04 UTC, raman-m commented on src/DependencyInjection/ConfigurationBuilderExtensions.cs
> +        return AddOcelotJsonFile(builder, json, PrimaryConfigFile, optional, reloadOnChange);
The old `primaryConfigFile` argument must be applied here❗

2026-07-03 18:04 UTC, raman-m commented on src/DependencyInjection/ConfigurationBuilderExtensions.cs
> +    private static void MergeConfig(JToken to, JToken from, bool isGlobal)
No point in keeping static methods private. Make them public — no risk for future dev and support.

2026-07-03 18:04 UTC, raman-m commented on src/Errors/OcelotError.cs
> +    public OcelotError()
This error is quite abstract and lacks context. There is no information about its origin.
Sender or creator details should be attached to provide more clarity.

2026-07-03 18:04 UTC, raman-m commented on unit/Controllers/FileConfigurationControllerTests.cs
> +        Assert.IsType<string>(actual.Value);
Lost type info.

2026-07-04 17:14 UTC, raman-m commented on acceptance/Configuration/ConfigurationBuilderExtensionsTests.cs
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1183/commits/e566a4648f266b99be608f466f9ef183ae929081 ✔️

2026-07-04 18:21 UTC, raman-m commented on src/Administration/FileConfigurationController.cs
> +            return BadRequest(e.GetMessages());
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1183/commits/4cd6f83efae914762887bc87c4b88dbf104d28d1 ✔️

2026-07-04 18:23 UTC, raman-m commented on src/Administration/FileConfigurationController.cs
> +            return BadRequest(e.GetMessages());
`ToString` returns too long string, introduced `ToShortString` returning "Type name : message".
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1183/commits/4cd6f83efae914762887bc87c4b88dbf104d28d1 ✔️

2026-07-04 18:26 UTC, raman-m commented on src/Configuration/Repository/FileConfigurationPoller.cs
> +                _logger.LogWarning(() => $"{nameof(Poll)}: Error getting {nameof(FileConfiguration)} -> {e.AllMessages}.");
Rolled back previous logging of complete exception data &rarr; `{e}` was an implicit call to `e.ToString()` due to string interpolation.
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1183/commits/4cd6f83efae914762887bc87c4b88dbf104d28d1 ✔️

2026-07-05 10:20 UTC, raman-m commented on src/DependencyInjection/ConfigurationBuilderExtensions.cs
> +    private static void MergeConfig(JToken to, JToken from, bool isGlobal)
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1183/commits/00125210f1b2730d6e9d2e54b55d6befaed0d172 ✔️

2026-07-05 12:45 UTC, raman-m commented on src/DependencyInjection/ConfigurationBuilderExtensions.cs
> +    public static IConfigurationBuilder AddOcelot(this IConfigurationBuilder builder, JObject fileConfiguration)
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1183/commits/eedf90dcf629e9701a08c2983e394825058eaec3 ✔️

2026-07-05 12:45 UTC, raman-m commented on src/DependencyInjection/ConfigurationBuilderExtensions.cs
> +        => SerializeToFile(builder, fileConfiguration);
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1183/commits/eedf90dcf629e9701a08c2983e394825058eaec3 ✔️

2026-07-05 12:46 UTC, raman-m commented on src/DependencyInjection/ConfigurationBuilderExtensions.cs
> +        return AddOcelotJsonFile(builder, json, PrimaryConfigFile, optional, reloadOnChange);
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1183/commits/eedf90dcf629e9701a08c2983e394825058eaec3 ✔️

2026-07-05 13:10 UTC, raman-m commented on src/Errors/OcelotError.cs
> +    public OcelotError()
Doesn't matter actually. I've double checked the class and it has zero references. Thus, it can be deleted. There is another `UnknownError` type having the same purpose.
Removed in commit https://github.com/ThreeMammals/Ocelot/pull/1183/commits/66599cffb531ee6a649ac0814159874cc16cb865 ✔️

2026-07-11 17:17 UTC, raman-m approved these changes
## Ready for delivery ✅ 
- Code review ✔️ ✔️ 
- Unit tests ✔️ ✔️ ✔️ 
- Acceptance testing ✔️ ✔️ 
- Updated docs ✔️ ✔️ 
- Updated sample app ✔️ 🔥 

### TODO: Extend [Metadata](https://github.com/ThreeMammals/Ocelot/blob/develop/docs/features/metadata.rst) container with custom configuration properties and options

A new feature is available in `Program.cs`, either during application startup or when injecting `IConfiguration` from the DI container (in a running app). It would be beneficial to extend the [Metadata](https://github.com/ThreeMammals/Ocelot/blob/develop/docs/features/metadata.rst) feature by propagating custom properties/options after they are merged into the `Metadata` collection.
https://github.com/ThreeMammals/Ocelot/blob/7b38a95066e75c4ec2fb434ca91c3584282319c1/src/Configuration/MetadataOptions.cs#L54
https://github.com/ThreeMammals/Ocelot/blob/7b38a95066e75c4ec2fb434ca91c3584282319c1/src/Configuration/DownstreamRoute.cs#L124
This would enable reuse by custom middlewares and override capabilities in custom classes.

To implement this, the current [`*Creator` classes](https://github.com/search?q=repo%3AThreeMammals%2FOcelot+Creator+language%3AC%23&type=code&l=C%23) must be reviewed to ensure the `DownstreamRoute.MetadataOptions.Metadata` dictionary is initialized with the available custom properties and options. Currently, only the explicit properties manually defined in the `ocelot.json` [Metadata](https://ocelot.readthedocs.io/en/develop/features/metadata.html#schema) options are collected in the `Metadata` dictionary.

2026-07-11 17:22 UTC, merged

2026-07-11 18:07 UTC, raman-m commented
@jlukawska Thank you for your contribution in 2020. It has been a long journey of 6 years, but ultimately a successful one! 😍
Congrats on the merge! 🥳 This is a great feature 🚀