Update caching.rst
ThreeMammals/Ocelot pull request #1240
Opened 2020-05-24 08:30 UTC by EngRajabi

Fixes / New Feature #

## Proposed Changes

  -
  -
  -

2020-08-27 21:54 UTC, thiagoloureiro approved these changes

2023-07-19 18:26 UTC, raman-m commented
Related to #1167

2023-07-19 18:50 UTC, raman-m requested changes
We say "Thank you" in PRs/issues in our discussions/chats, without moving any discussions to the official documentation. LoL 🤣

2023-07-19 18:50 UTC, raman-m commented on docs/features/caching.rst
> +Thanks Mohsen Rajabi, PR `1167 <https://github.com/ThreeMammals/Ocelot/pull/1167>`_ add IMemoryCache Asp Core.
**First,**
The sentence contains English grammar mistakes!

**Second,**
Tom mentions people efforts by PR or Issue links in docs, but he doesn't mention real contributor's name!

**Third,**
It should be pasted after line 46 actually.

**Finally,**
A lack of information to introduce in docs. More wider and clear description of the related feature should be written.

2023-07-20 06:37 UTC, closed without merging