When the downstream service is not found, LeastConnection prompts War…
ThreeMammals/Ocelot pull request #1300
Opened 2020-07-25 07:44 UTC by HonghuiHu

…n and RoundRobin throws an exception

Fixes / New Feature #

## Proposed Changes

  -
  -
  -

2020-07-25 07:51 UTC, HonghuiHu commented
When the downstream service is not found, LeastConnection prompts Warn and RoundRobin throws an exception。
![image](https://user-images.githubusercontent.com/39977344/88452138-bffe1880-ce8e-11ea-9a13-26bbd632cc1b.png)

2023-07-19 11:06 UTC, raman-m requested changes
Hi Honghui!
Thanks for your interest in Ocelot!

Let's start the discussion...
Currently I am not sure the PR contains right solution for extra requests coming from browsers. 😄

2023-07-19 11:06 UTC, raman-m commented on src/Ocelot/LoadBalancer/LoadBalancers/RoundRobin.cs
> +                    // When the downstream service is not found, LeastConnection prompts Warn and RoundRobin throws an exception, eg: /favicon.ico
Truly speaking this case of icon should not be processed by this method.
Can we filter such cases in upper contexts?

2023-07-19 11:06 UTC, raman-m commented on src/Ocelot/LoadBalancer/LoadBalancers/RoundRobin.cs
> +                    return new ErrorResponse<ServiceHostAndPort>(new ServicesAreEmptyError($"Services were empty for {httpContext.Request.Path}"));
Does this error returning fix the bug with exception generation by global exception handler?
How will `ErrorResponse` prevent exception generating in upper contexts?

2023-08-02 11:47 UTC, raman-m requested changes
Missing unit tests and at least one acceptance test for the user's scenario!

2023-10-03 21:14 UTC, raman-m commented
@ggnaegi 
Look at this PR please!
What do you think?..

2023-10-04 06:32 UTC, ggnaegi reviewed
@raman-m I think the problem was that round robin behaved differently than other load balancers.
We would expect ``` new ErrorResponse<ServiceHostAndPort>(new ServicesAreEmptyError("There were no services in LoadBalancer")); ``` if no services are available. It seems to me that this is now fixed in the develop branch and this PR could be closed.

``` c#
 var services = await _servicesDelegate?.Invoke() ?? new List<Service>();

            if (services?.Count != 0)
            {
                lock (_lock)
                {
                    if (_last >= services.Count)
                    {
                        _last = 0;
                    }

                    var next = services[_last++];
                    return new OkResponse<ServiceHostAndPort>(next.HostAndPort);
                }
            }

            return new ErrorResponse<ServiceHostAndPort>(new ServicesAreEmptyError($"There were no services in {nameof(RoundRobin)} during {nameof(Lease)} operation."));
```
https://github.com/ThreeMammals/Ocelot/blob/develop/src/Ocelot/LoadBalancer/LoadBalancers/RoundRobin.cs

2023-10-30 09:35 UTC, raman-m commented
@HonghuiHu
This issue is outdated, and it is already fixed in **develop** branch.
Please, sync your forked repo, and/or download Ocelot v[20.0](../releases) NuGet package

2023-10-30 09:35 UTC, closed without merging