Change upstream regex to account for blank placeholders
ThreeMammals/Ocelot pull request #1333
Opened 2020-09-04 00:33 UTC by AndyConlisk

Fixes #658

## Proposed Changes

  - To fix the issue mentioned in #658 this adds an additional regex and to account for blank last placeholder.

2023-08-05 15:38 UTC, raman-m commented
@AndyConlisk 
Thanks for the PR!
The [feature branch](/AndyConlisk/Ocelot/tree/master) (**master**) has been [rebased](#event-10015455639) onto [ThreeMammals:develop](../tree/develop)!
And we have the green build.
So, we can go with code review now...

---

I don't see **develop** branch in [your fork](https://github.com/DanHarltey/Ocelot/branches)! Your fork is too old.

Could you [Sync fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) please? So, new **develop** branch will occur with all top commits!

Could you [add me as collaborator](/AndyConlisk/Ocelot/settings/access) to your forked repo please? I will create **develop** branch and make it default.

2023-08-05 15:40 UTC, raman-m commented
@skyflyer Hi Miha!
As an issue author,
Could you review the code of this solution please?

2023-08-05 16:50 UTC, AndyConlisk commented
> @AndyConlisk Thanks for the PR! The [feature branch](/AndyConlisk/Ocelot/tree/master) (**master**) has been [rebased](#event-10015455639) onto [ThreeMammals:develop](../tree/develop)! And we have the green build. So, we can go with code review now...
> 
> I don't see **develop** branch in [your fork](https://github.com/DanHarltey/Ocelot/branches)! Your fork is too old.
> 
> Could you [Sync fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) please? So, new **develop** branch will occur with all top commits!
> 
> Could you [add me as collaborator](/AndyConlisk/Ocelot/settings/access) to your forked repo please? I will create **develop** branch and make it default.

@raman-m

I added you as a collaborator to my fork. Please let me know if there is anything else you need me to do.

Thank you

2023-08-05 17:26 UTC, skyflyer commented
> @skyflyer Hi Miha!
> As an issue author,
> Could you review the code of this solution please?

Hello @raman-m!

Unfortunately, I'm not really acquainted with the code base and won't be able to either reproduce the error or test the fix right now. Sorry about that.

But, I will have a look at reproducing the scenario later, if that helps.

2023-08-06 13:48 UTC, skyflyer commented
So, I'm not sure if my rationale is sound, but this does not seem to work, at least not for the case I reported in the issue.

First, do understand, that we're not using Ocelot anymore (the project that was the consumer of this library unfortunately died some time ago). Also understand that I'm not in a position to really review the code, as I'm not really acquainted with the codebase nor the roadmap and the design of the library. So take the following comments with that in mind. :smile:

The general idea was that ocelot lib would route requests coming to `/api` to some services running without the `/api` prefix. In other words, requests coming to http://localhost:5000/api would be routed (or proxied would be a better term, I think) to http://localhost:8000/ and by that logic, requests coming to http://localhost:5000/api/foo would be routed to http://localhost:8000/api/foo.

In order to verify this behaviour, I cloned the develop branch from the main repo and "squash merged" the PR 1333 into that, so the changes are applied on top of the latest develop bits.

I then used a simple config (see below) and tried to request the resources. I've setup python's simple http server (`python3 -m http.server 8000`) in the parent directory where `Ocelot` (the repository) and `OcelotDemo` (the test program) were hosted.

1. request to http://localhost/api works ✅
2. request to http://localhost/api/ does not work ❌
    * error message: Failed to match Route configuration for upstream path: /api/, verb: GET.
4. request to http://localhost/api/foo works ✅
5. request to http://localhost/api/OcelotDemo/ocelot.json works ✅


<details><summary>Simple config</summary>

```json
{
    "Routes": [
        {
        "DownstreamPathTemplate": "/{id}",
        "DownstreamScheme": "http",
        "DownstreamHostAndPorts": [
            {
                "Host": "localhost",
                "Port": 8000
            }
        ],
        "UpstreamPathTemplate": "/api/{id}",
        "UpstreamHttpMethod": [ "Get", "Post" ]
        }
    ],
    "GlobalConfiguration": {
        "BaseUrl": "https://localhost:5000"
    }
}
```
</details>

2023-08-07 07:24 UTC, RaynaldM approved these changes

2023-08-14 14:11 UTC, raman-m commented
> @AndyConlisk commented [on Aug 5](#issuecomment-1666552607)

Thanks!
All that's left to do is making it default. 👇 

![image](https://github.com/ThreeMammals/Ocelot/assets/10501504/29f6e059-c8f1-41e2-93c2-46a37a899693)

2023-08-14 14:36 UTC, AndyConlisk commented
@raman-m I have made the develop branch to be the default branch.

2023-08-14 14:40 UTC, raman-m commented
@skyflyer commented [on Aug 6](#issuecomment-1666866611):
> 2. request to http://localhost/api/ does not work ❌
    * error message: Failed to match Route configuration for upstream path: /api/, verb: GET.

Thanks for user scenarios.
Yeah, we will test this scenario too.
And, on my opinion, all user's scenarios from your issue should be tested, but they are not, based on current source code.

2023-08-14 14:46 UTC, raman-m commented
> @RaynaldM approved these changes [on Aug 7](#pullrequestreview-1564708272)

Ray, why did you approve the PR?
There are no unit tests at all! 🤣 
Even a beautiful code without tests should not be approved. 😃

2023-08-14 16:17 UTC, raman-m requested changes
@AndyConlisk 
Although the code looks solid, but it can be improved. 👇 

---
### ${\color{orange}There\ are\ no\ new\ tests!}$
The new code blocks are not covered by unit tests.
There are no unit tests for user scenarios from the linked issue.
Also, there are no acceptance tests to make sure Ocelot pipeline will handle all user scenarios correctly.

2023-08-14 16:17 UTC, raman-m commented on src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs
> +                        nextDelimiter = '?';
```suggestion
                        delimiter = nextDelimiter = '?';
```

2023-08-14 16:17 UTC, raman-m commented on src/Ocelot/DownstreamRouteFinder/UrlMatcher/UrlPathPlaceholderNameAndValueFinder.cs
> +                {
The code for this **if**-block was copied from lines 26-46.
Based on the function of code snippet, why not to define private helper-method to be reused in both places?

2023-08-14 16:21 UTC, raman-m commented
### Related to
- #145 
- #158 
- 9ba57f8ba654f66d5515fb96b7500ec67bf846c7

2023-10-26 17:29 UTC, raman-m commented
@AndyConlisk Do you have time to fix [code review issues](#pullrequestreview-1577061541)?
Do you have an intention to write unit tests at all?

2023-11-07 00:08 UTC, AndyConlisk commented
I don't know when I will have time to write the new unit tests. I can try in the near future, but I can't give a solid commitment at this time.

2023-11-08 09:12 UTC, raman-m commented
@AndyConlisk commented [on Nov 7](#issuecomment-1797062176)

Lazy bones! :wink:

2024-06-15 13:48 UTC, raman-m commented
Duplicate of #1911

2024-06-15 13:49 UTC, raman-m commented
### Original issue #658 was fixed by #1911

2024-06-15 13:49 UTC, closed without merging