Improvement regex
ThreeMammals/Ocelot pull request #1348
Opened 2020-10-06 18:17 UTC by EngRajabi

## Improvement regex

  - set option compile
  - set timeout
  - set static object(Regex class is in mutable)

microsfot linke => https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices

2020-10-07 06:31 UTC, Hossein-Edraki approved these changes
It's Ok

2020-11-08 09:22 UTC, EngRajabi commented
@TomPallister

2020-11-15 11:02 UTC, VahidTajari submitted a review, later dismissed

2020-11-20 06:59 UTC, WeihanLi commented
What if timeout happens? Timeout maybe not good practice here.

2020-11-20 07:15 UTC, EngRajabi commented
Setting timeout is one of the necessary tasks of using regex. When a timeout occurs, it is best to run the entire project involved and not respond to others.

2020-11-20 07:27 UTC, WeihanLi commented
Is there some reason for considering `100ms` as the regex timeout, and how could the client update the timeout config if the client wanna use a longer timeout?

2020-11-20 07:51 UTC, EngRajabi commented
timeout is not customizable by the customer. Like many other settings. It was 100 ms when I adjusted it according to the tests I had. But we can decide here and change this time. We can set this time to 500 ms. If we do not receive an answer at this time, it is better not to involve the whole project in its implementation and let it respond to other requests.

2023-07-20 06:57 UTC, EngRajabi reviewed
review done

2023-07-20 12:51 UTC, raman-m commented
Dear Mohsen,

Why did you [merge develop branch from your fork into the feature branch](#commits-pushed-ff1dbb6)?
I meant these commits: https://github.com/ThreeMammals/Ocelot/pull/1348/commits/ff1dbb6c1d9925a08e910c7c4d1f79fd6017c216 https://github.com/ThreeMammals/Ocelot/pull/1348/commits/5b336cdda05a6474eb964b5668272ed6f3b358df
It was unnecessary because [I did the merge of ThreeMammals:develop](#commits-pushed-329d2c3) in https://github.com/ThreeMammals/Ocelot/pull/1348/commits/329d2c373dfbd7619d2d570a77327bb6d3b02268.
After that I trigger pipeline to make a valid green build for commit https://github.com/ThreeMammals/Ocelot/pull/1348/commits/03a70b32b23f00f41ab93d14e7bbf75a775066a3.

Now there is no build at all and pipeline cannot run new build.
The pipeline cannot recognize **develop** branch because you have juggled all commits in a wrong way.

Could you [fix/update your fork develop branch](/EngRajabi/Ocelot/pull/8#issuecomment-1643837790) please first?

After that we will try to fix pipeline triggering by rebasing current feature branch onto **develop** one.

2023-07-21 10:14 UTC, EngRajabi reviewed
I did Branch Develop on Branch as Rebase. Does this solve this problem?

2023-07-22 10:54 UTC, raman-m commented
![image](https://github.com/ThreeMammals/Ocelot/assets/10501504/911cdf55-4901-45ea-a798-44e1008c8777)

Now I see develop and it has [zero diff](../compare/develop...EngRajabi:Ocelot:develop), but the branch is not default. ☝️ 
You have to go to [repo settings](/EngRajabi/Ocelot/settings) and make **develop** branch as default!
I hope that should help to fix the problem of builds, because all builds are built for develop branch (auto) and master (manually).
Currently I don't see that pipeline was triggered for [top commit](/EngRajabi/Ocelot/commits/improvement_regex).
Maybe an empty or tiny commit will be required to trigger the pipeline after making develop branch default.

2023-07-22 13:15 UTC, EngRajabi reviewed
change something for build

2023-07-22 14:16 UTC, raman-m commented
Feature branch has been rebased onto develop!
The build has been passed!

Going to start code review...

2023-07-28 07:22 UTC, RaynaldM approved these changes

2023-08-01 19:47 UTC, wast approved these changes

2023-08-03 11:34 UTC, raman-m requested changes
I see three major issues with current code:
- `TimeSpan.FromMilliseconds(100)`. The hardcode of `100` is detected. Milliseconds constant should be a constant, and public static. Moving to some common options static class is highly desired.
- No catching and processing of the `RegexMatchTimeoutException` object being generated by all `Regex` objects. A `try-catch` constructions should be provided.
- No unit tests which cover new behavior of `Regex`. So, `RegexMatchTimeoutException` exception case should be tested.

Hope this doc will be helpful: [Defining a Time-Out Value](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex?view=net-7.0#define_timeout),
to understand current issues.

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/Configuration/Validator/FileConfigurationFluentValidator.cs
> +            var matches = _regExPlaceholder.Matches(upstreamPathTemplate);
No catching and processing of the `RegexMatchTimeoutException` exception.

Will it result to unhandled exception by app domain?
Wil it be caught by upper context?

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/Authorization/ClaimsAuthorizer.cs
> +                    var match = _regexAuthorize.Match(required.Value);
No catching and processing of the `RegexMatchTimeoutException` exception.

Will it result to unhandled exception by app domain?
Wil it be caught by upper context?

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/Configuration/Validator/RouteFluentValidator.cs
> +        private static readonly Regex _daysRegEx = new Regex("^[0-9]+d", RegexOptions.Compiled, TimeSpan.FromMilliseconds(100));
Hardcode has detected!
The `100` milliseconds constant should be public static.

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/Configuration/Validator/RouteFluentValidator.cs
> +                   || _daysRegEx.Match(period).Success;
No catching and processing of the `RegexMatchTimeoutException` exception.

Will it result to unhandled exception by app domain?
Wil it be caught by upper context?

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs
> +            Regex.CacheSize += 100;
What is the default, current value of the cache in runtime?
So, why did you increase this property value?

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs
> +            Regex.CacheSize += 100;
Do you consider the `AddOcelot` methos as an entry point for entire Ocelot pipeline, and for all regex-objects of the app domain?

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs
> +                .Where(fi => _reg.IsMatch(fi.Name) && (fi.Name != excludeConfigName))
No catching and processing of the `RegexMatchTimeoutException` exception.

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs
> +            DownstreamRequest downstreamRequest, List<PlaceholderNameAndValue> templatePlaceholderNameAndValues)
Why was that changed? 😉 
There is no need to change! No new code!

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs
> +                        (key, oldValue) => oldValue);
No catching and processing of the `RegexMatchTimeoutException` exception.

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs
>          }
Still wonder...
What are the changes? 🤣

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs
> +            Response<DownstreamPath> dsPath)
I see zero changes in method signature!
But, If you split parameters, I suggest to put each parameter onto new line 👇 
```suggestion
        private (string Path, string Query) CreateServiceFabricUri(
            DownstreamRequest downstreamRequest,
            DownstreamRoute downstreamRoute,
            List<PlaceholderNameAndValue> templatePlaceholderNameAndValues,
            Response<DownstreamPath> dsPath)
```

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs
> +                   downstreamRoute.UseServiceDiscovery;
Zero changes!
Revert this fake change plz!

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs
> +                        templatePlaceholderNameAndValues);
Revert this!

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs
> +                downstreamRequest.Query = pathAndQuery.Query;
Zero changes!
Revert to previous code!

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/Infrastructure/ConfigAwarePlaceholders.cs
> +            => _regex.Replace(key, string.Empty);
No catching and processing of the `RegexMatchTimeoutException` exception.

2023-08-03 11:34 UTC, raman-m commented on src/Ocelot/Values/UpstreamPathTemplate.cs
> +                    _regex.AddOrUpdate(template, new Regex(template, RegexOptions.Compiled | RegexOptions.Singleline, TimeSpan.FromMilliseconds(100)),
No catching and processing of the `RegexMatchTimeoutException` exception.

2023-08-03 11:34 UTC, raman-m commented on test/Ocelot.UnitTests/Cache/CacheKeyGeneratorTests.cs
There are no unit tests for new approach of using Regex.
Time out should be tested!

2023-08-03 11:34 UTC, raman-m commented on test/Ocelot.UnitTests/CacheManager/OutputCacheMiddlewareRealCacheTests.cs
Regex Time out event should be tested!

2023-08-04 11:33 UTC, EngRajabi commented
@raman-m 
Hello, I read some of your reviews, but since there were many, I will answer you in one post.
1- In the case of TimeSpan.FromMilliseconds(100), if the work is not done in 100 milliseconds, the work will not continue. Regarding the RegexMatchTimeoutException, I ask you what happens in the current situation where we have not set the timeout??? When we don't have a timeout, the requests wait so much that they receive errors, and the CPU and computing resources are busy. But with my changes, a timeout error occurs, which probably returns the error code 500 in the output. This behavior is better than the current default behavior.
2- In the case of Regex.CacheSize += 100. Its default value is 15. According to the following document
https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices
This amount is very, very low for large projects and causes the cache to be cleared very often and this causes our patterns to come out of the cache.
3- Regarding format code changes. These changes are not my work. If you have looked, people changed my code.

2023-08-09 17:20 UTC, raman-m commented
> @EngRajabi commented [on Aug 4, 2023](#issuecomment-1665463285)

It is better to reply in own thread of each code review issue...

---

>  When we don't have a timeout, the requests wait so much that they receive errors, and the CPU and computing resources are busy. But with my changes, a timeout error occurs, **which probably returns the error code 500 in the output.** This behavior is better than the current default behavior.

Thanks for improvements! Current behavior has been improved. We've done with but...
I'm pretty sure that each `Match` method is not wrapped by any `try-catch` construction in upper contexts. That means, Yes, we have 99% `UnhandledException` which will be handled globally by current [OcelotPipelineExtensions](../blob/develop/src/Ocelot/Middleware/OcelotPipelineExtensions.cs#L40).
So, in this case we have error being handled, request has been failed, and records will be added by Ocelot loggers.
But... Instead of having error logged why not to improve user experience, and let the user know that current timeout value is low, and it is better to increase time out value. For example we could log a warning with all required metrics.
Finally, we can introduce some `Regex` helper for `Match` methods to process timeouts.

---

And, Could you add unit/acceptance test(s) please?

2023-08-09 17:57 UTC, raman-m commented
@WeihanLi commented [on Nov 20, 2020](#issuecomment-730959862):
> Is there some reason for considering 100ms as the regex timeout, and how could the client update the timeout config if the client wanna use a longer timeout?

I **wanna** develop your idea further! 😉
The `100ms` value will be OK if it covers all cases of `Regex`-matching inside of Ocelot core. But I am sure it doesn't. And, "[**Houston, we have a problem!**](https://www.youtube.com/watch?v=YwG4F-16Tno&t=40s)"  🤣 The problem with the `RegexMatchTimeoutException` objects being thrown by `Match` methods. 😩 

Regarding configuring of timeout value. Well... We could introduce one common configurable value for this option in [Best Practices for Regular Expressions in .NET](https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices#use-time-out-values):
> - Set a process-wide or AppDomain-wide value with code such as `AppDomain.CurrentDomain.SetData("REGEX_DEFAULT_MATCH_TIMEOUT", TimeSpan.FromMilliseconds(100));`.

What about such kind of `Regex` configuration?

2024-11-07 16:08 UTC, raman-m requested changes
### Ready for Final Code Review❕
The following items need verification:
- Define the `TimeSpan.FromMilliseconds(100)` parameter as a global static property to allow advanced configuration of this constant in C#. &rarr; **Docs**: [Use time-out values](https://learn.microsoft.com/en-us/dotnet/standard/base-types/best-practices-regex#use-time-out-values)
- Convert all `Regex` definitions to `GeneratedRegex`, following best practices in .NET 7+. See the `Ocelot.DependencyInjection.ConfigurationBuilderExtensions` class for an example, particularly the `SubConfigRegex()` method &rarr;
  https://github.com/ThreeMammals/Ocelot/blob/d310508aa28997a492eea4bc5cff889eb43014dd/src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs#L18-L24
  The preprocessor `if`-directive is necessary to accommodate support for `net6.0`, as well as for `net7.0` and `net8.0`
- Ensure that all `Regex` expressions are converted throughout the entire solution.

2024-11-07 16:13 UTC, raman-m commented
@EngRajabi Hello, Mohsen! Are you energized and ready to deliver this PR? 😄

2024-11-07 16:21 UTC, raman-m commented on src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs
> +                   downstreamRoute.UseServiceDiscovery;
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1348/commits/3c7781e7ceccf0a54e1feae91a07c78e12bcfa3d ✔️

2024-11-07 16:23 UTC, raman-m commented on src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs
> +            Response<DownstreamPath> dsPath)
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1348/commits/3c7781e7ceccf0a54e1feae91a07c78e12bcfa3d ✔️ 
The version from the develop branch was utilized.

2024-11-07 16:23 UTC, raman-m commented on src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs
>          }
Fixed in commit https://github.com/ThreeMammals/Ocelot/commit/3c7781e7ceccf0a54e1feae91a07c78e12bcfa3d ✔️

2024-11-07 16:25 UTC, raman-m commented on src/Ocelot/DownstreamUrlCreator/Middleware/DownstreamUrlCreatorMiddleware.cs
> +            DownstreamRequest downstreamRequest, List<PlaceholderNameAndValue> templatePlaceholderNameAndValues)
Fixed in commit https://github.com/ThreeMammals/Ocelot/commit/3c7781e7ceccf0a54e1feae91a07c78e12bcfa3d ✔️

2024-11-13 16:42 UTC, raman-m commented on src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs
> +            Regex.CacheSize += 100;
`AddOcelotBaseUrl` is `Obsolete`, so this is wrong location to handle the work.
Should be removed!

Fixed in https://github.com/ThreeMammals/Ocelot/pull/1348/commits/364d1b63ee39370f53c5e96bce2395d92b068be5 ✔️

2024-11-13 16:44 UTC, raman-m commented on src/Ocelot/DependencyInjection/ConfigurationBuilderExtensions.cs
> +            Regex.CacheSize += 100;
`100` hardcoded value should be removed in favor of a static property!

Fixed in https://github.com/ThreeMammals/Ocelot/pull/1348/commits/364d1b63ee39370f53c5e96bce2395d92b068be5 ✔️

2024-11-13 17:31 UTC, raman-m commented on src/Ocelot/Configuration/Validator/RouteFluentValidator.cs
> +        private static readonly Regex _daysRegEx = new Regex("^[0-9]+d", RegexOptions.Compiled, TimeSpan.FromMilliseconds(100));
Fixed in commit https://github.com/ThreeMammals/Ocelot/pull/1348/commits/68ef3a51989074f8ca6da43269d6ec948ceb6544 ✔️

2024-11-16 18:03 UTC, raman-m approved these changes
### Ready for Delivery ✅

2024-11-16 18:09 UTC, merged

2024-11-16 19:45 UTC, ggnaegi commented
Sorry, but I would have first moved to .NET 7 - 9 before... @RaynaldM your Thoughts?

2024-11-16 19:57 UTC, ggnaegi commented
@raman @RaynaldM Again, I would have prefered moving to .NET 7-9 before to reduce the complexity and ensure a better maintainability.

2024-12-13 15:28 UTC, raman-m commented
> @ggnaegi commented [Nov 16, 2024](https://github.com/ThreeMammals/Ocelot/pull/1348#issuecomment-2480759693)

Please update to the desired .NET version in your forked repository.
To minimize complexity and ensure better maintainability, we adhere to the standard Microsoft .NET support lifecycle, specifically the [.NET and .NET Core Support Policy](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core) &rarr;  **.NET 7** &rarr; **End of support** on May 14, 2024❗ 
Our official end of .NET 6, 7 support is merged PRs #2220 #2221 &rarr; version [23.4.2](https://github.com/ThreeMammals/Ocelot/releases/tag/23.4.2)

**P.S.** Ocelot is an open-source project, just like .NET framework. You would be correct if Ocelot were a commercial project, but it is not.