Update HeaderFindAndReplaceCreator.cs
ThreeMammals/Ocelot pull request #1424
Opened 2021-01-27 19:30 UTC by fku-

Second parameter of Substring was wrong. Existing implementation works only for replacements at the beginning of a string (startOfPlaceholder = 0)

Fixes / New Feature #

## Proposed Changes

  - Allow replacements inside a header, not only at the beginning

2023-07-11 14:53 UTC, raman-m commented
Related to
- #1659

2023-08-23 12:18 UTC, RaynaldM approved these changes

2023-08-23 12:18 UTC, RaynaldM commented on src/Ocelot/Configuration/Creator/HeaderFindAndReplaceCreator.cs
>                  var endOfPlaceholder = replace.IndexOf("}", startOfPlaceholder, StringComparison.Ordinal);
```suggestion
                var endOfPlaceholder = replace.IndexOf('}', startOfPlaceholder, StringComparison.Ordinal);

```

2023-08-23 12:18 UTC, RaynaldM commented on src/Ocelot/Configuration/Creator/HeaderFindAndReplaceCreator.cs
>                  var endOfPlaceholder = replace.IndexOf("}", startOfPlaceholder, StringComparison.Ordinal);
and you could do same thing at line 74

2023-09-30 15:18 UTC, raman-m requested changes

2023-09-30 15:18 UTC, raman-m commented on src/Ocelot/Configuration/Creator/HeaderFindAndReplaceCreator.cs
> +using System.Collections.Generic;
Redundant!
```suggestion
```

2023-09-30 15:39 UTC, raman-m submitted a review, later dismissed

2023-09-30 17:33 UTC, raman-m approved these changes

2023-09-30 17:34 UTC, merged