Makes build cake 1.0.0 compatible
ThreeMammals/Ocelot pull request #1436
Opened 2021-02-12 04:17 UTC by abriening

Fixes / New Feature #

## Proposed Changes

  -
  -
  -

2021-06-22 09:57 UTC, amamei approved these changes

2021-06-22 09:59 UTC, gcaraman approved these changes

2021-06-22 10:36 UTC, CristaliS approved these changes

2023-06-30 19:47 UTC, raman-m commented
Please do the following:
- Merge [PR 1](https://github.com/abriening/Ocelot/pull/1)
- Rebase feature branch onto develop
- Resolve all merge conflicts

2023-08-23 17:18 UTC, raman-m commented
@abriening Hi Andrew!
I've tried to solve and resolve merge conflicts in better manner.
So, the [feature branch](/abriening/Ocelot/tree/cake-1-0-0-compatible) has been [rebased](#event-10172512646) onto [ThreeMammals:develop](../tree/develop) successfully!
I've kept all changes from target branch because it contains most actual config for builds.
But now, I don't see any changes in your PR at all. Small change on [line 444](../compare/develop...abriening:Ocelot:cake-1-0-0-compatible#diff-c6eace5a70f0c2d920dfa97e988d4cad3d0131dd2b029bb2646c96222e866cf8R444). Is it relevant?
Also, Cake Tool has version [3.0.0](../blob/develop/.config/dotnet-tools.json#L6) now, not **1.0.0** as it's requested in PR.
**It seems your PR is obsolete now, right?**

2023-08-24 00:39 UTC, abriening commented
My PRs were ignored for several years. I've moved to https://github.com/microsoft/reverse-proxy instead of ocelot.

2023-08-28 14:42 UTC, raman-m commented
Andrew!
Sorry for ignoring your PR. The owner doesn't care about this project since 2020.
Can we close the PR because of applied fix by owner in other commits?

2023-09-30 15:00 UTC, raman-m requested changes

2023-09-30 15:04 UTC, raman-m requested changes

2023-09-30 15:04 UTC, raman-m commented on build.cake
> +	var json = $"{{ \"tag_name\": \"{versioning.NuGetVersion}\", \"target_commitish\": \"master\", \"name\": \"{versioning.NuGetVersion}\", \"body\": \"{ReleaseNotesAsJson()}\", \"draft\": true, \"prere
```suggestion
	var json = $"{{ \"tag_name\": \"{versioning.NuGetVersion}\", \"target_commitish\": \"main\", \"name\": \"{versioning.NuGetVersion}\", \"body\": \"{ReleaseNotesAsJson()}\", \"draft\": true, \"prerelease\": true }}";
```
We make releases on **main** which protected!
**master** is not protected anymore, and [this branch was removed](../branches/all).

2023-10-09 19:21 UTC, closed without merging