reopened pr #1030
ThreeMammals/Ocelot pull request #1576
Opened 2022-05-09 12:54 UTC by OnSive

PR: #1030 
> Fixes / New Feature # Fixes exceptions being thrown because of already closed WebSockets when the state is both updated by the source and destination.
> 
> ## Proposed Changes
> * Only close websocket connection if the current state allows it
> 
> Stacktrace of exception that is intended to fix:
> 
> `requestId: 0HLPTRFNQ4IJE:00000001, previousRequestId: no previous request id, message: Exception caught in global error handler, exception message: The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived', exception stack: at System.Net.WebSockets.WebSocketValidate.ThrowIfInvalidState(WebSocketState currentState, Boolean isDisposed, WebSocketState[] validStates) at System.Net.WebSockets.ManagedWebSocket.CloseOutputAsync(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at Ocelot.WebSockets.Middleware.WebSocketsProxyMiddleware.PumpWebSocket(WebSocket source, WebSocket destination, Int32 bufferSize, CancellationToken cancellationToken) at Ocelot.WebSockets.Middleware.WebSocketsProxyMiddleware.Proxy(HttpContext context, String serverEndpoint) at Ocelot.WebSockets.Middleware.WebSocketsProxyMiddleware.Invoke(DownstreamContext context) at Ocelot.DownstreamUrlCreator.Middleware.DownstreamUrlCreatorMiddleware.Invoke(DownstreamContext context) at Ocelot.LoadBalancer.Middleware.LoadBalancingMiddleware.Invoke(DownstreamContext context) at Ocelot.Request.Middleware.DownstreamRequestInitialiserMiddleware.Invoke(DownstreamContext context) at Ocelot.Middleware.Multiplexer.Multiplexer.Fire(DownstreamContext context, OcelotRequestDelegate next) at Ocelot.Middleware.Multiplexer.Multiplexer.Multiplex(DownstreamContext context, ReRoute reRoute, OcelotRequestDelegate next) at Ocelot.DownstreamRouteFinder.Middleware.DownstreamRouteFinderMiddleware.Invoke(DownstreamContext context) at Ocelot.Middleware.Pipeline.MapWhenMiddleware.Invoke(DownstreamContext context) at Ocelot.Errors.Middleware.ExceptionHandlerMiddleware.Invoke(DownstreamContext context)`

2023-05-11 16:56 UTC, raman-m requested changes
I do NOT see any fixes!
I see extra code only with extra post-action.

2023-05-11 16:56 UTC, raman-m commented on src/Ocelot/WebSockets/Middleware/WebSocketsProxyMiddleware.cs
> +                    }
Simple logical challenge:
How many times will the action be applied here?
Once or twice?

The action is `CloseOutputAsync`.

2023-05-11 16:56 UTC, raman-m commented on src/Ocelot/WebSockets/Middleware/WebSocketsProxyMiddleware.cs
> +                        }
Why do you apply the same action twice?

The action is `CloseOutputAsync`.

2023-05-12 00:36 UTC, OnSive commented
I'm closing this PR as I can't remember what it was actually about and the original author is actively communicating on #1030

2023-05-12 00:36 UTC, closed without merging