Ts/issue 729 fix
ThreeMammals/Ocelot pull request #1749
Opened 2023-10-19 16:18 UTC by ks1990cn

Fixes / New Feature #
- Fixing issue for status code 404, when content length is large than body size. will be displaying 413 status code ("Entity Payload too large"). 
- Considered scenario when application is hosted on Kestrel , IIS or Http.Sys and have different options configured as per host server.
for example - 
```
builder.WebHost.UseHttpSys(options =>
{
    options.MaxRequestBodySize = 60000000;
});
```
Above code have `MaxRequestBodySize  `configured manually (default is ~28.6MB), so changes will handle this case too.

## Proposed Changes
- I have done manual testing, writing test case to fake server host was tough, as per my research on aspnetcore there is no exposed way to directly write this fake server test.
- I also faced issue with access level of `ToByteArray` of `RequestMapper`, so I could have marked it null and `ByteArrayContent` constructor have given me error and hence I could have tested it.
- Open for discussion how we can test this functionality :D

2023-10-20 09:57 UTC, raman-m commented
Tanmay,
The issue #729 is about sticky sessions! Are you sure your PR is related to #729 ?
It seems the number is wrong...

2023-10-20 10:01 UTC, raman-m commented
I found it! The issue is #749 😺 
- #749

2023-10-20 10:05 UTC, ks1990cn commented
> I found it! The issue is #749 😺
> 
> * [Bad error handling for IOException while reading incoming request body #749](https://github.com/ThreeMammals/Ocelot/issues/749)

Sorry! correct its 749. Thank you

2023-10-25 07:00 UTC, ggnaegi requested changes
Hello

I think, you could improve the code a bit. I would recommend creating a service for the exception handling, otherwise you are mixing concerns in the RequestMapper class.

You will be then able to write some unit tests for your service.

Acceptance tests are missing.

2023-10-25 16:40 UTC, ks1990cn commented on src/Ocelot/Request/Mapper/RequestMapper.cs
> +        private bool PayloadTooLargeOnAnyHostedServer(HttpRequest request, Exception ex)
Acknowledged and made related changes.

2023-10-25 16:40 UTC, ks1990cn commented on src/Ocelot/Request/Mapper/RequestMapper.cs
> +        public RequestMapper(IOptions<HttpSysOptions> httpSysOptions, IOptions<KestrelServerOptions> kerstrelServerOptions, IOptions<IISServerOptions> iISOptions,IServer server)
Acknowledged and made related changes.

2023-10-26 09:01 UTC, ggnaegi commented
@ks1990cn @raman-m  Hello, I took now a bit of time to create an acceptance test, and I realized that the implementation is WAAAAAAAAAAAAAY too complicated (and it's impossible to get the KestrelServer from IServer, because you will get KestrelServerImpl first). Kestrel and other servers will return you a ```BadHttpRequestException``` with status code 413. So the issue here, is that the exception is wrapped and hidden in the UnmappableRequestError.  A rethinking of the exception handling is needed... 

The issue here can be easily be fixed with:
```c#
catch (BadHttpRequestException badHttpRequest)
            {
                return badHttpRequest.StatusCode == 413 ? new ErrorResponse<HttpRequestMessage>(new PayloadTooLargeError(badHttpRequest)) : new ErrorResponse<HttpRequestMessage>(new UnmappableRequestError(badHttpRequest));
            }
            catch (Exception ex)
            {
                return new ErrorResponse<HttpRequestMessage>(new UnmappableRequestError(ex));
            }
```
Again, it's only a patch, imho, the exception should bubble up to a central exception handler.
The acceptance test:
``` c#
[Fact]
        public void should_return_status_413_when_exceeding_body_max_size()
        {
            var port = RandomPortFinder.GetRandomPort();

            var configuration = new FileConfiguration
            {
                Routes = new List<FileRoute>
                {
                    new()
                    {
                        DownstreamPathTemplate = "/",
                        UpstreamPathTemplate = "/",
                        UpstreamHttpMethod = new List<string> { "Post" },
                        DownstreamHostAndPorts = new List<FileHostAndPort>
                        {
                            new()
                            {
                                Host = "localhost",
                                Port = port,
                            },
                        },
                        DownstreamScheme = "http",
                    },
                },
            };

            this.Given(x => x.GivenThereIsAServiceRunningOnNoExceptions($"http://localhost:{port}"))
                .And(x => _steps.GivenThereIsAConfiguration(configuration))
                .And(x => _steps.GivenOcelotIsRunningOnKestrelWithCustomBodyMaxSize(1024))
                .When(x => _steps.WhenIPostUrlOnTheApiGateway("/", new ByteArrayContent(File.ReadAllBytes(@"C:\Users\gnaegu\Desktop\test45.txt"))))
                .Then(x => _steps.ThenTheStatusCodeShouldBe(413))
                .BDDfy();
        }
```
Kestrel Server Implementation
```c#
public void GivenOcelotIsRunningOnKestrelWithCustomBodyMaxSize(long customBodyMaxSize)
        {
             var kestrelServer = Host.CreateDefaultBuilder()
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseKestrel().ConfigureKestrel((_, options) =>
                        {
                            options.Limits.MaxRequestBodySize = customBodyMaxSize;
                        })
                        .ConfigureAppConfiguration((hostingContext, config) =>
                        {
                            config.SetBasePath(hostingContext.HostingEnvironment.ContentRootPath);
                            var env = hostingContext.HostingEnvironment;
                            config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: false)
                                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: false);
                            config.AddJsonFile(_ocelotConfigFileName, optional: true, reloadOnChange: false);
                            config.AddEnvironmentVariables();
                        })
                        .ConfigureServices(s =>
                        {
                            s.AddOcelot();
                        })
                        .Configure(app =>
                        {
                            app.Use(async (_, next) =>
                            {
                                await next.Invoke();
                            });
                            app.UseOcelot().Wait();
                        })
                        .UseUrls("http://localhost:5001");
                }).Build();
             kestrelServer.Start();

             _ocelotClient = new HttpClient
             {
                 BaseAddress = new Uri("http://localhost:5001"),
             };
        }
```

2023-10-26 09:05 UTC, ggnaegi requested changes
Please look at my comment. The implementation is overkill, this can be easily be fixed.

2023-10-26 11:51 UTC, raman-m commented
Guys, who is our hero?
I'll get back to this funny thread after current release...
Keep conversation ongoing! ✌️😁

2023-10-26 12:02 UTC, ggnaegi commented
> Guys, who is our hero?
> I'll get back to this funny thread after current release...
> Keep conversation ongoing! ✌️😁

Well, not really. I'm just tired of this $%^%&*% error handling.

2023-10-26 13:20 UTC, ks1990cn commented
Ah! didn't noticed that it already gives 413 in exception, I remember it was giving me 404 only (Maybe I didn't noticed right). Correct it can be done directly.
If you are ready @ggnaegi, you can go ahead. Converting it to draft. Thanks for taking look @ggnaegi .

2023-10-26 13:20 UTC, closed without merging

2023-10-30 12:48 UTC, raman-m commented
Open.. close... open... close... I'm going crazy with you guys 😃 
What is the follow up after closing this PR?
What is the result?