#1172 Default CacheKeyGenerator
ThreeMammals/Ocelot pull request #1849
Opened 2023-12-09 16:08 UTC by raman-m

## Follows up #1172 
- #1172 

## Related to #1808 
- #1808 

During [22.0](https://github.com/ThreeMammals/Ocelot/releases/tag/22.0.0) release feature #1172 was excluded from delivery list. Now it is time to deliver it once again with some enhancements after team's discussion.

## Proposed Changes
  - Disable request content hashing for performance reasons
  - Introduce new `EnableRequestBodyHashing` property of the `CacheOptions` class
  - Make `CacheKeyGenerator` default via class renaming

2023-12-09 16:20 UTC, raman-m commented
@ggnaegi You are welcome to review code of this PR!

We have some dev plan on this:
- your comments: [1st](https://github.com/ThreeMammals/Ocelot/pull/1172#issuecomment-1830081902) and [2nd](https://github.com/ThreeMammals/Ocelot/pull/1172#issuecomment-1830740495)
- after merging this PR you'll create new PR on top of this code

Please review!

2023-12-09 16:23 UTC, raman-m commented
Should I add acceptance tests? 😇 😃

2023-12-09 17:06 UTC, ggnaegi requested changes
@raman-m a few changes i would recommend. Please no virtual, since we don't have any use cases with overridden properties and methods. The only use case here is testing...

2023-12-09 17:09 UTC, ggnaegi commented
> Should I add acceptance tests? : 😇 😋

😇

2023-12-11 07:31 UTC, RaynaldM approved these changes

2023-12-11 07:31 UTC, RaynaldM commented on src/Ocelot/Request/Middleware/DownstreamRequest.cs
> +        public virtual HttpHeaders Headers { get; }
agree with you @ggnaegi

2023-12-12 15:02 UTC, raman-m commented on src/Ocelot/Cache/DefaultCacheKeyGenerator.cs
> +            if (!downstreamRequest.HasContent || !options.EnableRequestBodyHashing)
Fixed in https://github.com/ThreeMammals/Ocelot/pull/1849/commits/5305b306859f82dd08430a576d3ed12469adf820

2023-12-12 17:43 UTC, raman-m commented on src/Ocelot/Request/Middleware/DownstreamRequest.cs
> +        public virtual HttpHeaders Headers { get; }
Good recommendation!
Fixed in https://github.com/ThreeMammals/Ocelot/pull/1849/commits/faaed441064ecc81e309ffe09adc0a95d9c60da3 ✔️

2023-12-12 17:44 UTC, raman-m commented on src/Ocelot/Request/Middleware/DownstreamRequest.cs
> +        public virtual string OriginalString { get; }
Removed in https://github.com/ThreeMammals/Ocelot/pull/1849/commits/faaed441064ecc81e309ffe09adc0a95d9c60da3

2023-12-12 17:44 UTC, raman-m commented on src/Ocelot/Request/Middleware/DownstreamRequest.cs
> +        public virtual bool HasContent { get => _request?.Content != null; }
Removed in https://github.com/ThreeMammals/Ocelot/pull/1849/commits/faaed441064ecc81e309ffe09adc0a95d9c60da3

2023-12-12 17:45 UTC, raman-m commented on src/Ocelot/Request/Middleware/DownstreamRequest.cs
> +        public virtual HttpRequestMessage Request { get => _request; }
Removed in https://github.com/ThreeMammals/Ocelot/pull/1849/commits/faaed441064ecc81e309ffe09adc0a95d9c60da3

2023-12-12 17:46 UTC, raman-m commented on test/Ocelot.UnitTests/Cache/DefaultCacheKeyGeneratorTests.cs
> +        private readonly Mock<DownstreamRequest> _downstreamRequest;
Good recommendation!
Fixed in https://github.com/ThreeMammals/Ocelot/pull/1849/commits/faaed441064ecc81e309ffe09adc0a95d9c60da3 ✔️

2023-12-12 17:46 UTC, raman-m commented on test/Ocelot.UnitTests/Cache/DefaultCacheKeyGeneratorTests.cs
> +        {
Done by https://github.com/ThreeMammals/Ocelot/pull/1849/commits/faaed441064ecc81e309ffe09adc0a95d9c60da3 ✔️

2023-12-12 17:47 UTC, raman-m commented on test/Ocelot.UnitTests/Cache/DefaultCacheKeyGeneratorTests.cs
> +    internal class HttpHeadersStub : HttpHeaders
Stub class has been removed in https://github.com/ThreeMammals/Ocelot/pull/1849/commits/faaed441064ecc81e309ffe09adc0a95d9c60da3 ✔️

2023-12-12 17:48 UTC, raman-m commented on test/Ocelot.UnitTests/Cache/DefaultCacheKeyGeneratorTests.cs
> +            const string content = nameof(should_generate_cache_key_happy_path);
Added new `GivenHasContent` helper in https://github.com/ThreeMammals/Ocelot/pull/1849/commits/faaed441064ecc81e309ffe09adc0a95d9c60da3 ✔️

2023-12-12 17:51 UTC, raman-m commented
>@ggnaegi suggested changes [on Dec 9](https://github.com/ThreeMammals/Ocelot/pull/1849#pullrequestreview-1773723485)
>@RaynaldM approved these changes [on Dec 11](https://github.com/ThreeMammals/Ocelot/pull/1849#pullrequestreview-1774415198)

Code review issues have been **fixed** ✅

2023-12-13 17:56 UTC, raman-m commented
> @ggnaegi commented [on Dec 9](https://github.com/ThreeMammals/Ocelot/pull/1849#issuecomment-1848584274)

Acceptance test has been [added](https://github.com/ThreeMammals/Ocelot/blob/follow-up-1172/test/Ocelot.AcceptanceTests/Caching/CachingTests.cs#L116-L153)! ✔️ 

By default body content is not hashed.
@ggnaegi  Looks good now?

2023-12-13 18:21 UTC, ggnaegi approved these changes

2023-12-13 19:21 UTC, raman-m commented
Ready for delivery! ✔️

2023-12-14 09:18 UTC, merged

2024-12-11 16:47 UTC, wast commented on src/Ocelot/Configuration/CacheOptions.cs
> +        public bool EnableContentHashing { get; }
I think this was breaking change that causes wrong caches with POST requests with payload. Rolled back to version 21 where there is no issue. Haven't had time to confirm, but I'm 90% sure. Gonna try to add a unit test in a PR.

2024-12-13 12:53 UTC, raman-m commented
Dear @wast, don't remove your comments: better to discuss what was happen. Anyway I have email notifications.

> ```diff
> +        public bool EnableContentHashing { get; }
> ```
> I think this was breaking change that causes wrong caches with POST requests with payload. Rolled back to version 21 where there is no issue. Haven't had time to confirm, but I'm 90% sure. Gonna try to add a unit test in a PR.
> 

The problem was reported in #2054 #2059, and the bug was fixed by #2058 with merging on May 13, 2024, see commit https://github.com/ThreeMammals/Ocelot/commit/6e9a975fae3b26229c3f0b3c1a475a7b05e95fee please. So, the fix was delivered in version [23.3.0](https://github.com/ThreeMammals/Ocelot/releases/tag/23.3.0).

> Gonna try to add a unit test in a PR.

What is the purpose? The bug was fixed by #2058! Therefore, please use the latest version and specify [global options](https://ocelot.readthedocs.io/en/latest/features/caching.html#global-configuration). Enjoy!

2024-12-13 12:54 UTC, wast commented
Comment was deleted as it wasn't relevant anymore.