Fix a bug in HttpRequesterMiddleware.cs,
ThreeMammals/Ocelot pull request #1953
Opened 2024-01-30 10:38 UTC by masoud-bahrami

BadRequest should be logged as debug!

Fixes / New Feature #

## Proposed Changes

  -
  -
  -

2024-01-30 11:59 UTC, raman-m commented
@masoud-bahrami 
Now Masoud, please explain what did you do in this PR?
I see a small refactoring here... Nothing more!

**Have you read our [development process](https://ocelot.readthedocs.io/en/latest/building/releaseprocess.html) docs?**

2024-01-31 11:45 UTC, masoud-bahrami commented
@raman-m In the CreateLogBasedOnResponse method due to `if (response.Data?.StatusCode <= HttpStatusCode.BadRequest)`  logic, BadRequest will be logged as `Information`.

As you can see, In the next branch of if, `else if (response.Data?.StatusCode >= HttpStatusCode.BadRequest)`  again HttpStatusCode.BadRequest is checked.

It's like these 
` If (a <= 400) do something
else If (a >= 400) do something else`

2024-02-16 17:43 UTC, raman-m commented
@masoud-bahrami 
> `BadRequest` should be logged as debug!

Did you mean as warning? 😉 to be logged by `LogWarning` method?
OK... Now I see!..
It is a small comparison typo `<=` in the code but resulting to real bug...

2024-02-16 17:53 UTC, raman-m requested changes
Please cover this scenario by unit test(s)!
Will be good to write acceptance tests too

2024-02-27 15:22 UTC, raman-m approved these changes

2024-02-27 15:35 UTC, merged